version: '2'

services:
  mariadb:
    container_name: d7d-db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - 7306:3306
    volumes:
      - mysqldata:/var/lib/mysql/data

  php:
    container_name: d7d-web
    build: ./config/php-fpm
    links:
      - mariadb:mysql
    volumes:
      - .:/var/www

  nginx:
    container_name: d7d-nginx
    image: nginx:latest
    links:
      - php
    ports:
      - '7080:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/web

volumes:
  mysqldata: {}
