[xdebug]
zend_extension=xdebug.so
xdebug.mode=debug
; Port 9003 is the default since PhpStorm 2020.3 and Xdebug 3.
; If using an older IDE, change to 9000.
xdebug.client_port=9003
xdebug.client_host=host.docker.internal
